# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{remodel-h}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Lossen"]
  s.date = %q{2010-07-21}
  s.default_executable = %q{redis-monitor.rb}
  s.description = %q{persist your objects to redis hashes.}
  s.email = %q{tim@lossen.de}
  s.executables = ["redis-monitor.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/redis-monitor.rb",
     "docs/docco.css",
     "docs/remodel.html",
     "example/book.rb",
     "lib/remodel-h.rb",
     "lib/remodel/entity.rb",
     "lib/remodel/has_many.rb",
     "lib/remodel/mapper.rb",
     "remodel-h.gemspec",
     "test/helper.rb",
     "test/test_entity.rb",
     "test/test_many_to_many.rb",
     "test/test_many_to_one.rb",
     "test/test_mappers.rb",
     "test/test_monkeypatches.rb",
     "test/test_one_to_many.rb",
     "test/test_one_to_one.rb"
  ]
  s.homepage = %q{http://github.com/tlossen/remodel}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{remodel variant which uses hashes}
  s.test_files = [
    "test/helper.rb",
     "test/test_entity.rb",
     "test/test_many_to_many.rb",
     "test/test_many_to_one.rb",
     "test/test_mappers.rb",
     "test/test_monkeypatches.rb",
     "test/test_one_to_many.rb",
     "test/test_one_to_one.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

